import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import WhatsApp from "./whatsapp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Freja Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="relative h-full">
        <header className="shadow sticky top-0 left-0 right-0 z-10">
          <Navbar />
        </header>
        <main>
          <WhatsApp />
          {children}
        </main>
        <footer className="bg-neutral-200 text-center lg:text-left">
          <div className="p-4 text-center flex justify-between px-8">
            <a
              className="text-neutral-800 hover:underline"
              href="https://instagram.com"
            >
              © 2023 Copyright Freja Company
            </a>
            <a
              href="https://github.com/labs-company"
              target="_blank"
              className="hover:underline"
            >
              By Labs Company
            </a>
          </div>
        </footer>
      </body>
    </html>
  );
}
